

langs = {
    "afrikaans":"af",
    "basque":"eu",
    "bulgarian":"bg",
    "catalan":"ca",
    "arabic (egypt)":"ar-EG",
    "arabic (jordan)":"ar-JO",
    "arabic (kuwait)":"ar-KW",
    "arabic (lebanon)":"ar-LB",
    "arabic (qatar)":"ar-QA",
    "arabic (uae)":"ar-AE",
    "arabic (morocco)":"ar-MA",
    "arabic (iraq)":"ar-IQ",
    "arabic (algeria)":"al-DZ",
    "arabic (bahrain)":"ar-BH",
    "arabic (lybia)":"ar-LY",
    "arabic (oman)":"ar-OM",
    "arabic (saudi arabia)":"ar-SA",
    "arabic (tunisia)":"ar-TN",
    "arabic (yemen)":"ar-YE",
    "czech":"cs",
    "dutch":"nl-NL",
    "english (australia)":"en-AU",
    "english (canada)":"en-CA",
    "english (india)":"en-IN",
    "english (new zealand)":"en-NZ",
    "english (south africa)":"en-ZA",
    "english (uk)":"en-GB",
    "english (us)":"en-US",
    "finnish":"fi",
    "french":"fr-FR",
    "galician":"gl",
    "german":"de-DE",
    "hebrew":"he",
    "hungarian":"hu",
    "icelandic":"is",
    "italian":"it-IT",
    "indonesian":"id",
    "japanese":"ja",
    "korean":"ko",
    "latin":"la",
    "mandarin chinese":"zh-CN",
    "traditional taiwan":"zh-TW",
    "simplified chinese":"zh-CN",
    "simplified hong kong":"zh-HK",
    "yue chinese (traditional hong kong)":"zh-yue",
    "malaysian":"ms-MY",
    "norwegian":"no-NO",
    "polish":"pl",
    "pig latin":"xx-piglatin",
    "portuguese":"pt-PT",
    "portuguese (brasil)":"pt-BR",
    "romanian":"ro-RO",
    "russian":"ru",
    "serbian":"sr-SP",
    "slovak":"sk",
    "spanish (argentina)":"es-AR",
    "spanish (bolivia)":"es-BO",
    "spanish (chile)":"es-CR",
    "spanish (colombia)":"es-CO",
    "spanish (costa rica)":"es-CR",
    "spanish (dominican republic)":"es-DO",
    "spanish (ecuador)":"es-EC",
    "spanish (el salvador)":"es-SV",
    "spanish (guatemala)":"es-GT",
    "spanish (honduras)":"es-HN",
    "spanish (mexico)":"es-MX",
    "spanish (nicaragua)":"es-NI",
    "spanish (panama)":"es-PA",
    "spanish (paraguay)":"es-PY",
    "spanish (peru)":"es-PE",
    "spanish (puerto rico)":"es-PR",
    "spanish (spain)":"es-ES",
    "spanish (us)":"es-US",
    "spanish (uruguay)":"es-UY",
    "spanish (venezuela)":"es-VE",
    "swedish":"sv-SE",
    "turkish":"tr",
    "zulu":"zu"
}

langs2 = {
    'afrikaans': 'af', 
    'albanian': 'sq', 
    'amharic': 'am', 
    'arabic': 'ar', 
    'armenian': 'hy', 
    'azerbaijani': 'az', 
    'basque': 'eu', 
    'belarusian': 'be', 
    'bengali': 'bn', 
    'bosnian': 'bs', 
    'bulgarian': 'bg', 
    'catalan': 'ca', 
    'cebuano': 'ceb', 
    'chichewa': 'ny', 
    'chinese (simplified)': 'zh-cn', 
    'chinese (traditional)': 'zh-tw', 
    'corsican': 'co', 
    'croatian': 'hr', 
    'czech': 'cs', 
    'danish': 'da', 
    'dutch': 'nl', 
    'english': 'en', 
    'esperanto': 'eo', 
    'estonian': 'et', 
    'filipino': 'tl', 
    'finnish': 'fi', 
    'french': 'fr', 
    'frisian': 'fy', 
    'galician': 'gl', 
    'georgian': 'ka', 
    'german': 'de', 
    'greek': 'el', 
    'gujarati': 'gu', 
    'haitian creole': 'ht', 
    'hausa': 'ha', 
    'hawaiian': 'haw', 
    'hebrew': 'he', 
    'hindi': 'hi', 
    'hmong': 'hmn',
    'hungarian': 'hu', 
    'icelandic': 'is', 
    'igbo': 'ig', 
    'indonesian': 'id', 
    'irish': 'ga', 
    'italian': 'it', 
    'japanese': 'ja', 
    'javanese': 'jw', 
    'kannada': 'kn', 
    'kazakh': 'kk', 
    'khmer': 'km',
    'korean': 'ko', 
    'kurdish (kurmanji)': 'ku', 
    'kyrgyz': 'ky', 
    'lao': 'lo', 
    'latin': 'la', 
    'latvian': 'lv', 
    'lithuanian': 'lt', 
    'luxembourgish': 'lb', 
    'macedonian': 'mk', 
    'malagasy': 'mg', 
    'malay': 'ms', 
    'malayalam': 'ml',
    'maltese': 'mt', 
    'maori': 'mi', 
    'marathi': 'mr', 
    'mongolian': 'mn', 
    'myanmar (burmese)': 'my', 
    'nepali': 'ne', 
    'norwegian': 'no',
    'odia': 'or', 
    'pashto': 'ps', 
    'persian': 'fa', 
    'polish': 'pl', 
    'portuguese': 'pt', 
    'punjabi': 'pa', 
    'romanian': 'ro', 
    'russian': 'ru', 
    'samoan': 'sm', 
    'scots gaelic': 'gd', 
    'serbian': 'sr', 
    'sesotho': 'st', 
    'shona': 'sn', 
    'sindhi': 'sd', 
    'sinhala': 'si', 
    'slovak': 'sk', 
    'slovenian': 'sl', 
    'somali': 'so', 
    'spanish': 'es', 
    'sundanese': 'su', 
    'swahili': 'sw', 
    'swedish': 'sv', 
    'tajik': 'tg', 
    'tamil': 'ta', 
    'telugu': 'te', 
    'thai': 'th', 
    'turkish': 'tr', 
    'ukrainian': 'uk', 
    'urdu': 'ur', 
    'uyghur': 'ug',
    'uzbek': 'uz',  
    'vietnamese': 'vi', 
    'welsh': 'cy', 
    'xhosa': 'xh', 
    'yiddish': 'yi', 
    'yoruba': 'yo', 
    'zulu': 'zu'
}
